# Generated by Django 3.2.4 on 2021-06-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20210621_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestionmodel',
            name='answers',
            field=models.CharField(default=1, max_length=240),
            preserve_default=False,
        ),
    ]
